# ModelArguments
model_name_or_path: gpt2
dataset_name_or_path: sample_grouped_owt_morph15k_50k_2048 # /pfss/mlde/workspaces/mlde_wsp_MorphPiece/data/fineweb-edu/grouped_owt_morph15k_50k_1024
tokenizer_name_or_path: /pfss/mlde/workspaces/mlde_wsp_MorphPiece/data/tokenizers_50k/gpt2-owt-morph15k
seq_len: 1024
attn_implementation: flash_attention_2 # eager, flash_attention_2, sdpa

# TrainingArguments
accelerator_config:
    dispatch_batches: null
    even_batches: true
    gradient_accumulation_kwargs: null
    non_blocking: false
    split_batches: false
    use_seedable_sampler: true
adafactor: false
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1.0e-08
auto_find_batch_size: false
batch_eval_metrics: false
bf16: true # changed from default false
bf16_full_eval: false
data_seed: 42
dataloader_drop_last: false
dataloader_num_workers: 8 # changed from default 0
dataloader_persistent_workers: false
dataloader_pin_memory: true
dataloader_prefetch_factor: null
ddp_backend: null
ddp_broadcast_buffers: null
ddp_bucket_cap_mb: null
ddp_find_unused_parameters: null
ddp_timeout: 1800
debug: []
deepspeed: configs/ds_configs/ds_config_stage1.json # changed from default null
disable_tqdm: false
dispatch_batches: null
do_eval: false
do_predict: false
do_train: false
eval_accumulation_steps: null
eval_delay: 0
eval_do_concat_batches: true
eval_on_start: false
eval_steps: null
eval_strategy: 'steps'
eval_use_gather_object: false
evaluation_strategy: null
fp16: false
fp16_backend: auto
fp16_full_eval: false
fp16_opt_level: O1
fsdp: []
fsdp_config:
    min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
    xla_fsdp_v2: false
fsdp_min_num_params: 0
fsdp_transformer_layer_cls_to_wrap: null
full_determinism: false
gradient_accumulation_steps: 1
gradient_checkpointing: false # changed from default false
gradient_checkpointing_kwargs:
    use_reentrant: False
greater_is_better: null
group_by_length: false
half_precision_backend: auto
hub_always_push: false
hub_model_id: null
hub_private_repo: false
hub_strategy: every_save
hub_token: <HUB_TOKEN>
ignore_data_skip: false
include_inputs_for_metrics: false
include_num_input_tokens_seen: false
include_tokens_per_second: false
jit_mode_eval: false
label_names: null
label_smoothing_factor: 0.0
learning_rate: 6.0e-04 # changed from default 
length_column_name: length
load_best_model_at_end: false
local_rank: -1 # changed from default 0
log_level: passive
log_level_replica: warning
log_on_each_node: true
logging_dir: /pfss/mlde/workspaces/mlde_wsp_MorphPiece/det_exps/tb_logs/
logging_first_step: false
logging_nan_inf_filter: true
logging_steps: 10
logging_strategy: steps
lr_scheduler_kwargs: {'pct_cooldown': 0.8, 'step_cooldown': 90}
lr_scheduler_type: constant_with_warmup # changed from default linear
max_grad_norm: 1.0
max_steps: 100 # changed from default -1
metric_for_best_model: null
mp_parameters: ''
neftune_noise_alpha: null
no_cuda: false
num_train_epochs: -1 # changed from default 3.0
optim: adamw_torch
optim_args: null
optim_target_modules: null
output_dir: /pfss/mlde/workspaces/mlde_wsp_MorphPiece/det_exps/gpt2_morph15k_1024_test
overwrite_output_dir: false
past_index: -1
per_device_eval_batch_size: 64 # changed from default 8
per_device_train_batch_size: 64 # changed from default 8
prediction_loss_only: false
push_to_hub: false
push_to_hub_model_id: null
push_to_hub_organization: null
hub_token: <PUSH_TO_HUB_TOKEN>
ray_scope: last
remove_unused_columns: true
report_to:
- tensorboard
#- wandb
restore_callback_states_from_checkpoint: false
resume_from_checkpoint: null
run_name: gpt2_morph15k_1024_test
save_on_each_node: false
save_only_model: false
save_safetensors: true
save_steps: 500
save_strategy: steps
save_total_limit: null
seed: 42
skip_memory_metrics: true
split_batches: null
tf32: null
torch_compile: true # changed from default
torch_compile_backend: null
torch_compile_mode: null # changed from default null
torch_empty_cache_steps: null
torchdynamo: null
tpu_metrics_debug: false
tpu_num_cores: null
use_cpu: false
use_ipex: false
use_legacy_prediction_loop: false
use_mps_device: false
warmup_ratio: 0.0
warmup_steps: 10 # changed from default 0
weight_decay: 0.1 # changed from default 0.0